"""empty message

Revision ID: 846ad7a83a6c
Revises: a613e4141609
Create Date: 2020-12-21 04:04:06.181386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846ad7a83a6c'
down_revision = 'a613e4141609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venu_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venu_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id', 'venu_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
