"""empty message

Revision ID: fb6002607c0b
Revises: c5c71539151c
Create Date: 2020-12-22 10:21:16.537871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6002607c0b'
down_revision = 'c5c71539151c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('talent_description', sa.String(length=600), nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'talent_description')
    # ### end Alembic commands ###
