"""empty message

Revision ID: 313b0f1d31e7
Revises: e0a6d3a191bb
Create Date: 2020-12-19 12:01:23.102300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313b0f1d31e7'
down_revision = 'e0a6d3a191bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
